huge, no more managers and zellij is not working for me

diff --git a/bin/videowall b/bin/videowall
--- a/bin/videowall
+++ b/bin/videowall
@@ -1,9 +1,17 @@
 #!/usr/bin/env bash
-# Show a video as wallpaper.
-# Prepare a video: videowall -p <video> [-t <limit video to some second>] (this sets the video too)
-# Set the video: videowall
-# Quit: videowall -q
-# The prepared video is located in $HOME/.videowall
+help='
+  ▌ ▐·▪  ·▄▄▄▄  ▄▄▄ .      ▄▄▌ ▐ ▄▌ ▄▄▄· ▄▄▌  ▄▄▌
+ ▪█·█▌██ ██▪ ██ ▀▄.▀·▪     ██· █▌▐█▐█ ▀█ ██•  ██•
+ ▐█▐█•▐█·▐█· ▐█▌▐▀▀▪▄ ▄█▀▄ ██▪▐█▐▐▌▄█▀▀█ ██▪  ██▪
+  ███ ▐█▌██. ██ ▐█▄▄▌▐█▌.▐▌▐█▌██▐█▌▐█ ▪▐▌▐█▌▐▌▐█▌▐▌
+ . ▀  ▀▀▀▀▀▀▀▀•  ▀▀▀  ▀█▄▀▪ ▀▀▀▀ ▀▪ ▀  ▀ .▀▀▀ .▀▀▀
+
+Show a video as wallpaper.
+Prepare a video: videowall -p <video> [-t <limit video to some second>] (this sets the video too)
+Set the video: videowall
+Quit: videowall -q
+The prepared video is located in ~/.videowall
+'
 
 video=
 limit=
@@ -13,7 +21,7 @@ while getopts p:l:qh opt; do
     p) video="$OPTARG" ;;
     l) limit="-t $OPTARG" ;;
     q) quit=true ;;
-    h) echo "Usage: videowall [-p '<video>' -l '<limit_in_seconds>']" && exit 1 ;;
+    h) echo "$help" && exit 0 ;;
     *) echo "Usage: videowall [-p '<video>' -l '<limit_in_seconds>']" && exit 1 ;;
     esac
 done
@@ -22,24 +30,33 @@ if [[ $(pgrep -c videowall) -gt 1 ]]; then
     pgrep --oldest videowall | xargs kill -9
 fi
 
-if $quit; then pgrep videowall | xargs kill -9; fi
+if $quit; then
+    pgrep videowall | xargs kill -9
+fi
 
 if [[ -n $video ]]; then
     echo "Preparing video... 🧙"
-    rm -rf "$HOME/.videowall" && mkdir -p "$HOME/.videowall"
-    eval "(ffmpeg -y -ss 00:00:00.000 $limit -i '$video' '$HOME/.videowall/%d.jpg' > /dev/null 2>&1) || echo 'Error! Check options and run again'"
+    rm -rf "$HOME/.videowall"
+    mkdir -p "$HOME/.videowall"
+    eval "(ffmpeg -y -ss 00:00:00.000 $limit -i '$video' '$HOME/.videowall/%d.png' > /dev/null 2>&1) || echo 'Error! Check options and run again'"
 fi
 
 if [[ -d "$HOME/.videowall" ]]; then
     total_files=$(($(find "$HOME/.videowall" | wc -l) - 1))
-    if [[ -z $total_files ]]; then echo "Prepare a video first!" && exit 1; fi
+    if [[ -z $total_files ]]; then
+        echo "Prepare a video first!"
+        exit 1
+    fi
     iterator=1
     (while true; do
-        hsetroot -cover "$HOME/.videowall/${iterator}.jpg" >/dev/null 2>&1
+        hsetroot -cover "$HOME/.videowall/${iterator}.png" >/dev/null 2>&1
         iterator=$((iterator + 1))
-        if [[ $iterator -gt $total_files ]]; then iterator=1; fi
+        if [[ $iterator -gt $total_files ]]; then
+            iterator=1
+        fi
     done) &
     disown
 else
-    echo "Prepare a video first!" && exit 1
+    echo "Prepare a video first!"
+    exit 1
 fi
